config/routes.rb
HappyHealth::Application.routes.draw do

  

  get "blue_button/receive_attachment"

  captcha_route

  # get "users/show" => 'users#show'

  resources :notes

  #get '/users/sign_up' => 'static_pages#home'

  root to: "static_pages#home"

  get "/help" => 'static_pages#help'
  get "/about" => 'static_pages#about'

  post "/agree" => "offices#save_receipt", as: :receipt

  get "/add_medication" => 'forms#add_medication', as: :add_medication
  get "/remove_medication" => 'forms#remove_medication', as: :remove_medication
  get "/add_allergy" => 'forms#add_allergy', as: :add_allergy
  get "/remove_allergy" => 'forms#remove_allergy', as: :remove_allergy
  get "/add_problem" => 'forms#add_problem', as: :add_problem
  get "/remove_problem" => 'forms#remove_problem', as: :remove_problem

# Override Devise login
#  devise_for :users

  resources :users do
    resources :notes
    resources :forms do
      member do
        get 'printout'          
      end
      get 'print', on: :member
    end
    resources :appointments
  end

  #Session Routes
  get "enter" => 'sessions#new', as: 'enter'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match "/users/:id/sign_in" => "users#sign_in"

  resources :offices do
    resources :pdfs
  end

  #Yelp Office Search
  match "/yelp" => "offices#yelp_search"


  # InsuranceQuery GET resources & requests
  resources :insurance_queries do
    #get 'eligibility', on: :collection
    get 'eligibility', on: :member
    put 'service', on: :member
  end

  #********************** DOWNLOAD PDF BUTTON ****************************

  get "/appointment/download/:appointment_id" => 'offices#show', :as => :pdf
  get "/office/download/:office_id" => 'offices#show_pdf', :as => :office_pdf

  #########################################################################
  # AJAX get requests
  get "/appointment/doctors" => 'appointments#get_doctors'
  get "/appointment/pdf" => 'appointments#get_pdf'
  #########################################################################

  get "/doctors" => 'appointments#doctors', :as => :doctors

  match "/officeforms/new" =>'pdfs#new'

  # BlueButton Direct CCDA Attachment Routing
  post "/incoming/ccda/for/:to" => 'bluebutton#attachment'

end

app/models/note.rb
class Note < ActiveRecord::Base
	include PublicActivity::Common

	attr_accessible	:info,
									:user_id

	belongs_to :user
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.json

  before_filter :current_user

  def index
    @user = User.find_by_id(params[:user_id])
    @notes = @user.notes.order('updated_at desc').page(params[:page]).per(8)       #sort{|a,b| b.updated_at <=> a.updated_at}
    @current_page = "notes_show"
    # @notes = notes.sort!{|a,b| b.updated_at <=> a.updated_at}
    # @notes = Note.page(params[:page]).per(8)
    @note = Note.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    @user = User.find_by_id(params[:user_id])
    @note = Note.new
    @note.user_id = @user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(params[:note])
    @user = current_user
    @note.user_id = @user.id
    respond_to do |format|
      if @note.save
        @note.create_activity :create, parameters: {:info => @note.info}, owner: @note.user
        format.js
        format.html { redirect_to @user, notice: 'Note was successfully created.' }
        format.json { render json: @note, status: :created, location: @note }
      else
        format.html { render action: "new" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        @note.create_activity :update, parameters: {:info => @note.info}, owner: @note.user
        format.js
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @user = User.find_by_id(@note.user_id)

    @note.create_activity :destroy, parameters: {:info => @note.info}, owner: @note.user
    @note.destroy

    respond_to do |format|
      format.html { redirect_to user_notes_path(current_user.id) }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_activity.html.erb
<fieldset class="dashBackground">
	<%#= activity.owner if activity.owner %>
	<%= render_activity activity %>
	<legend><%= activity.created_at.localtime.strftime("%I:%M %P | %b %d, %Y") %></legend>
</fieldset>

app/views/notes/_form.html.erb
<!-- ************* FORM PARTIAL FOR ENTERING A NEW NOTE *************** -->

<%= form_for(note, :url => {:controller => 'notes', :action => "create"}, :remote => true) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="note_field">-->

<!-- MUST CHANGE FROM A TABLE TO FLOATING ELEMENTS FOR RESPONSIVE DESIGN & MOBILE UI -->

  <div class="note-field margin-top clearfix">
    <div class="inline">
      <%= f.text_area :info, :placeholder => "How do you feel right now?", class: "two_third_width note-text" %>
    </div>

      <%#= link_to 'Add New Note', '#', :class=> 'createButton' %>
      <%= f.submit "Post", class: "action-button note-button right" %>

  </div>

<% end %>

app/views/notes/_note.html.erb
<!-- ************* PARTIAL FOR STATIC, COMPLETED NOTE *************** -->


<fieldset id="note_<%= note.id %>" class="noteBackground">
	<legend><%= note.updated_at.localtime.strftime("%I:%M %P | %b %d, %Y") %></legend>

	<p id="note_<%= note.id %>"><%= note.info %>

		<span id="note-buttons">
			<%= link_to image_tag('trash-can-icon.jpg', size: '20x20' ), user_note_path(current_user.id, note.id), method: 'delete', remote: true, :class => "note-delete", :id => "note-buttons" %><%= link_to image_tag('pencil.png', size: '20x20'), edit_user_note_path(current_user.id, note.id), remote: true, :class => "note-edit", :id => 'note-buttons' %>
		</span>

	</p>
</fieldset>

app/views/notes/_note_edit.html.erb
<!-- ************* FORM PARTIAL FOR EDITING A PREVIOUSLY CONSTRUCTED NOTE *************** -->

<%= form_for(@note, :url => {:controller => 'notes', :action => "update"}, :remote => true) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="note_field">
   	<%#= f.text_field :info %>
  </div>
  <div class="actions">
    <%#= f.submit %>
  </div> -->

  <div class="note-field margin-top clearfix">
    <div class="inline">
      <%= f.text_area :info, class: "two_third_width" %>
    </div>

    <%= f.submit "Post", class: "submit-button right quarter_width" %>
  </div>

<% end %>

app/views/notes/create.js.erb
if($('article h1')[0].innerHTML == "Notes"){
	$("div#notes").prepend("<%= j(render @note) %>"); // ## Adds newly constructed Note container to the top of the Notes Index
	$("p#note_<%= @note.id %>").slideDown().effect('highlight');
}
else{
	$('div.dashAppointments').prepend("<%= j(render 'activity', :activity => PublicActivity::Activity.last) %>");
}

$("#note_info").val(""); // ** Clears out form

app/views/notes/destroy.js.erb
//$("fieldset#note_<%= @note.id+1%>.demoBackground").add();


$("fieldset#note_<%= @note.id %>.noteBackground").fadeOut();

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Back', current_user %>

app/views/notes/edit.js.erb
// ************* JS CODE FOR HIDING THEN RENDERING EDIT FORM ***************

$(".note_field").hide();

$("p#note_<%= @note.id %>").replaceWith("<%= j(render('note_edit')) %>")
$("a#note-buttons").hide();

app/views/notes/index.html.erb
<h1>Notes</h1>

<h2>Add notes as a personal reminder, or as an update to track problems, conditions or your mood.</h2>

<!-- <table class="margin-top table_row_two_thirds">
	<tr>
		<td> -->
			<%= render 'form', :note => @note %>
		<!-- </td>
		<td>
			<%#= link_to 'Add New Note', '#', :class=> 'createButton' %>
		</td>
	</tr>	
</table>   -->                            
	

<%= paginate(@notes)%>

<div id="notes" class="margin-top">
	<% if @notes != [] %>
			<%= render @notes %>		
	<% else %>
		<h2 class="reminder">You do not have any current notes. Make one now!</h2>
	<% end %>
</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Info:</b>
  <%= @note.info %>
</p>


<%= link_to 'Edit', edit_user_note_path(@note.user_id, @note) %> |
<%= link_to 'Back', current_user %>

<%= link_to 'Remove Note', user_note_path(@note.id), :method => "delete"%>

app/views/notes/update.js.erb
$("#edit_note_<%= @note.id %>").replaceWith("<%= j(render('form', note: @note)) %>"); // ## Replaces current Note container with a new Note form-field

$("fieldset#note_<%= @note.id %>.noteBackground").remove(); // ** Removes empty Note container following Updated Note

$("#edit_note_<%= @note.id %>").hide(); // ## Not sure what this is doing

$("div#notes").prepend("<%= j(render(@note)) %>"); // ** Container with newly created Edited Note

$("#note_info").show();


$("a").show();