config/routes.rb
HappyHealth::Application.routes.draw do

  

  get "blue_button/receive_attachment"

  captcha_route

  # get "users/show" => 'users#show'

  resources :notes

  #get '/users/sign_up' => 'static_pages#home'

  root to: "static_pages#home"

  get "/help" => 'static_pages#help'
  get "/about" => 'static_pages#about'

  post "/agree" => "offices#save_receipt", as: :receipt

  get "/add_medication" => 'forms#add_medication', as: :add_medication
  get "/remove_medication" => 'forms#remove_medication', as: :remove_medication
  get "/add_allergy" => 'forms#add_allergy', as: :add_allergy
  get "/remove_allergy" => 'forms#remove_allergy', as: :remove_allergy
  get "/add_problem" => 'forms#add_problem', as: :add_problem
  get "/remove_problem" => 'forms#remove_problem', as: :remove_problem

# Override Devise login
#  devise_for :users

  resources :users do
    resources :notes
    resources :forms do
      member do
        get 'printout'          
      end
      get 'print', on: :member
    end
    resources :appointments
  end

  #Session Routes
  get "enter" => 'sessions#new', as: 'enter'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match "/users/:id/sign_in" => "users#sign_in"

  resources :offices do
    resources :pdfs
  end

  #Yelp Office Search
  match "/yelp" => "offices#yelp_search"


  # InsuranceQuery GET resources & requests
  resources :insurance_queries do
    #get 'eligibility', on: :collection
    get 'eligibility', on: :member
    put 'service', on: :member
  end

  #********************** DOWNLOAD PDF BUTTON ****************************

  get "/appointment/download/:appointment_id" => 'offices#show', :as => :pdf
  get "/office/download/:office_id" => 'offices#show_pdf', :as => :office_pdf

  #########################################################################
  # AJAX get requests
  get "/appointment/doctors" => 'appointments#get_doctors'
  get "/appointment/pdf" => 'appointments#get_pdf'
  #########################################################################

  get "/doctors" => 'appointments#doctors', :as => :doctors

  match "/officeforms/new" =>'pdfs#new'

  # BlueButton Direct CCDA Attachment Routing
  post "/incoming/ccda/for/:to" => 'bluebutton#attachment'

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :name,
                  :doctors_attributes,
                  :address,
                  :city,
                  :state,
                  :zipcode,
                  :phone,
                  :fax,
                  :email,
                  :pdfs_attributes,
                  :abrv,
                  :latitude,
                  :longitude

  geocoded_by :full_address
  after_validation :geocode

  validates :name, :address, :city, :state, :presence => true

  has_many :doctors
  accepts_nested_attributes_for :doctors

  has_many :pdfs, dependent: :destroy
  accepts_nested_attributes_for :pdfs

  has_many :users, through: :appointments
  has_many :appointments

  def sorted_doctors
    self.doctors.sort {|a,b| a.title <=> b.title}
  end

  def full_address
    arry = [self.address, self.city, self.state, self.zipcode]
    arry.join(" ")
  end

end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  # GET /offices
  # GET /offices.json

  before_filter :logged_in
  before_filter :get_user
  before_filter :admin_user_access, except: [:index, :show, :save_receipt, :show_pdf]
  #before_filter :get_all_offices

  def index
    @offices = Office.all
    @appointment = Appointment.new
    @receipt = Receipt.new
    @current_page = "office_index"

    @office_form_partials = []
    @offices.each do |office|
      @office_form_partials << "appointments/forms/#{office.abrv}.pdf.html.erb"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  def save_receipt
    @receipt = Receipt.new(params[:receipt])
    if @receipt.save
      #redirect_to office_pdf_path(:office_id => @receipt.office_id)
      redirect_to office_path(:id => @receipt.office_id, :format => 'pdf')
    else
      redirect_to offices_path, :error => "Please check the terms of service agreement button"
    end
  end

  def show_pdf_old
    @office = Office.find_by_id(params[:office_id])
    @pdf = @office.pdfs
    @abrv = @office.abrv # => yields name of PDF form, _pdf.css.erb => name _pdf must match this name
    partial = "appointments/forms/_#{@abrv}"
    logger.debug "ABRV: #{@abrv}"
    @format = "pdf"
    # respond_to do |format|
      # format.pdf do
          #@file = render_to_string :pdf => "#{@office.name}", #Comment-out to enable 'View in separate tab' functionality; un-comment for direct-download of PDF
          render :pdf => "#{@office.name}", #Comment-out for direct-download of PDF functionality; un-comment to view PDF in separate window
                 :template => "#{partial}.pdf.html.erb",
                 :layout => "pdf.html.erb",
                 :page_size => "A4",
                 :encoding => "UTF-8",
                 :show_as_html => params[:debug].present?

          #send_data(@file, :filename => @office.name,  :type=>"application/pdf") #Comment-out to enable 'View in separate tab' functionality; un-comment for direct-download of PDF
          # For debugging, use
          # http://localhost:3000/appointments/9.pdf?office=mada&debug=1
          # http://localhost:3000/office/download/5?debug=1


      # end
    # end
  end

  def show_pdf 
    @office = Office.find_by_id(params[:office_id])
    @pdf = @office.pdfs
    @abrv = @office.abrv # => yields name of PDF form, _pdf.css.erb => name _pdf must match this name
    partial = "appointments/forms/#{@abrv}"
    logger.debug "ABRV: #{@abrv}"
    @format = "pdf"
    respond_to do |format|
      format.html
      format.pdf {
        html = render_to_string(
          :layout => "pdf.html.erb" , 
          :action => "show.html.erb", 
          :formats => [:html], 
          :handler => [:erb]
          )
        kit = PDFKit.new(html)
        kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/application.css"
        send_data(kit.to_pdf, 
                  :filename => "#{@office.name}.pdf", 
                  :type => 'application/pdf'
                  )
        return # to avoid double render call
      }
    end
  end
  
  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:office_id])
    @abrv = @office.abrv
    @partial_abrv = "#{@abrv}.pdf.html.erb"    
    logger.debug "Partial name = #{@partial_abrv} | CSS => #{get_stylesheet}"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office } 
      format.pdf {
        html = render_to_string(
          :layout => "pdf.html.erb" , 
          :action => "show.html.erb", 
          :formats => [:html], 
          :handler => [:erb]
          )
        kit = PDFKit.new(html)
        kit.stylesheets << get_stylesheet
        send_data(kit.to_pdf, 
                  :filename => "#{@office.name}.pdf", 
                  :type => 'application/pdf'
                  )
        return # to avoid double render call
      }     
    end
  end

  def get_stylesheet
    office = Office.find(params[:office_id])
    abrv = office.abrv
    if Rails.env.production?
      "#{Rails.root}/app/assets/stylesheets/#{abrv}.css.scss.erb"
    else
      "#{Rails.root}/app/assets/stylesheets/#{abrv}.css.scss.erb"
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new
    @office.pdfs << Pdf.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end    
  end

  def yelp_search
    client = Yelp::Client.new
    request = Yelp::V1::Phone::Request::Number.new(
      :phone_number => "3129229595",
        
      :yws_id => 'IjuGGlLHcxI94_kxNNQ63w'
      )
    
    @response = client.search(request)

    respond_to do |format|
      format.html
      format.json { render json: @response }      
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to offices_path, notice: 'Office was successfully created. Please add some office forms.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to new_office_pdf_path(@office), notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_clsma.pdf.html.erb
<!-- *************************************************

	HTML FOR PDF JQERY POPUP IN 'NEW APPOINTMENTS'

	**************************************************** -->

<style type="text/css">	

#container {
height: 1400px;
width: 1070px;
position: relative;
left: 0px;
top: 0px;
background-image: url('https://s3.amazonaws.com/happyhealthapp/assets/doctor2.jpg');
background-size: 1062px 1500px;
}

p {
margin: 0;
padding: 0;
font-color: red;
font-size: 16px;
font-weight: bold;
}

.pos {
   position: absolute;
}

/* --------------- LINE ONE ------------- */


.last-name{
	top: 425px;
	left: 240px;
}

.first-name {
	top: 425px;
	left: 430px;
}

.middle-init {
	top: 425px;
	left: 660px;
}

/* ------------- LINE TWO -------------- */

.user-address {
	top: 450px;
	left: 212px;
}

/* -------------- LINE THREE  ----------- */

.city{
	top: 475px;
	left: 190px;
}

.state {
	top: 475px;
	left: 340px;
}

.zip{
	top: 475px;
	left: 410px;
}

.phone{
	top: 475px;
	left: 560px;
}

.cell-phone{
	top: 475px;
	left: 765px;
}

/* ------------ LINE FOUR ------------- */

.dob {
	top: 500px;
	left: 245px;
}

.sex{
	top: 500px;
	left: 430px;
}

.marital-status{
	top: 500px;
	left: 585px;
}

.user-email{
	top: 500px;
	left: 665px;
}

/* ------------- LINE FIVE ------------ */

.ethnicity{
	top: 525px;
	left: 414px;
}

.race{
	top: 525px;
	left: 595px;
}

/* -------------- LINE SIX ------------ */



/* -------------- LINE SEVEN ------------ */

.employer-name{
	top: 663px;
	left: 295px;
}

/* ------------- LINE EIGHT ------------- */

.employer-address{
	top: 685px;
	left: 300px;
}

/* ------------- LINE NINE ------------- */

.employer-city{
	top: 713px;
	left: 195px;
}

.employer-state{
	top: 714px;
	left: 350px;
}

.employer-zip{
	top: 714px;
	left: 450px;
}

.work-phone{
	top: 714px;
	left: 580px;
}

/* ------------- LINE TEN ------------- */

.ss-number{
	top: 738px;
	left: 270px;
}

/* -------------- LINE ELEVEN -------- */

/* -------------- LINE TWELVE --------- */

#one.emergency-name{
	top: 808px;
	left: 350px;
}

#one.emergency-phone{
	top: 808px;
	left: 650px;
}

#one.emergency-relationship{
	top: 808px;
	left: 860px;
}

/* ------------- LINE THIRTEEN --------- */

/* ------------- LINE EIGHTEEN ---------- */


#one.insurance-company{
	top: 1065px;
	left: 335px;
}


/* -------------- LINE NINETEEN ---------- */

#one.policy-holder-last-name{
	top: 1091px;
	left: 585px;
}

#one.policy-holder-first-name{
	top: 1091px;
	left: 700px;
}

#one.insurance-birthdate{
	top: 1091px;
	left: 800px;
}

#one.insurer-relationship{
	top: 1091px;
	left: 900px;
}

/* ---------------- LINE TWENTY ----------- */

#one.group-number{
	top: 1115px;
	left: 320px;
}


#one.emergency-address, #two.emergency-name, #two.emergency-address, #two.emergency-relationship, #two.emergency-phone,
.date, .age, .referring-physician, .employment-status, .occupation, .employer-address, #one.insurance-policy-employer,
#one.insured-soc-number, #one.insurer-address, #two.insurance-policy-employer, #two.insured-soc-number, #two.insurer-address,
.employer-phone, #two.insurance-city, #two.policy-holder-first-name, #two.policy-holder-last-name, #two.insurance-birthdate,
#two.insurer-relationship, #two.group-name, #two.insured-soc-number, #two.insurance-company, #two.group-number,
#one.insurance-city{
	display: none;
}

</style>

<% user = current_user %>

<div id="pdf_container">
	<div id="container" class="form_dimension">

		<% if @format = "pdf" %>
			<%= render "appointments/pdf_form_buttons" %>
		<% end %>

		<div class="line-one first-name">
			<p>
				<%= user.form.personal.first_name %>
			</p>
		</div>
		<div class="line-one last-name">
			<p>
				<%= user.form.personal.last_name %>
			</p>
		</div>
		<div class="line-one age">
			<p>
				<%= user.form.personal.age %>
			</p>
		</div>
		<div class="line-one dob">
			<p>
				<%= user.form.personal.date_of_birth %>
			</p>
		</div>
		<div class="line-two user-address">
			<p>
				<%= user.form.personal.address %>
			</p>
		</div>
		<div class="line-two user-email">
			<p>
				<%= user.form.personal.email_address %>
			</p>
		</div>
		<div class="line-three city">
			<p>
				<%= user.form.personal.city %>
			</p>
		</div>
		<div class="line-three state">
			<p>
				<%= user.form.personal.state %>
			</p>
		</div>
		<div class="line-three zip">
			<p>
				<%= user.form.personal.zip_code %>
			</p>
		</div>
		<div class="line-three phone">
			<p>
				<%= user.form.personal.home_phone %>
			</p>
		</div>
		<div class="line-three social-security-number">
			<p>
				<%= user.form.personal.ss_number %>
			</p>
		</div>
		<div class="line-four employer-name">
			<p>
				<%= user.form.personal.employer %>
			</p>
		</div>
		<div class="line-four employer-address">
			<p>
				<%= user.form.personal.work_address %>
			</p>
		</div>
		<div class="line-four employer-phone">
			<p>
				<%= user.form.personal.employer_phone %>
			</p>
		</div>
		<div class="line-five employer-city">
			<p>
				<%= user.form.personal.employer_city %>
			</p>
		</div>
		<div class="line-five employer-state">
			<p>
				<%= user.form.personal.employer_state %>
			</p>
		</div>
		<div class="line-five employer-zip">
			<p>
				<%= user.form.personal.employer_zipcode %>
			</p>
		</div>
		<div class="line-six referring-physician">
			<p>
				<%= user.form.personal.referred_by %>
			</p>
		</div>
		<div class="line-ten insurance-company">
			<p>
				<%= user.form.insurances[0].company %>
			</p>
		</div>
		<div class="line-ten insurer-address">
			<p>
				<%= user.form.insurances[0].address %>
			</p>
		</div>
		<div class="line-eleven insurer-policy-holder">
			<p>
				<%= "#{user.form.insurances[0].subscribers_first_name} #{user.form.insurances[0].subscribers_last_name}" %>
			</p>
		</div>
		<div class="line-eleven insurer-coverage">
			<p>
				<%= user.form.insurances[0].title %>
			</p>
		</div>
		<div class="line-twelve insurance-policy-employer">
			<p>
				<%= user.form.insurances[0].subscribers_employer %>
			</p>
		</div>
		<div class="line-twelve insured-soc-number">
			<p>
				<%= user.form.insurances[0].social_security %>
			</p>
		</div>
		<div class="line-thirteen spouse-insurance-company">
			<p>
				<%#= user.form. %>
			</p>
		</div>
		<div class="line-thirteen spouse-insurer-address">
			<p>
				<%#= user.form.spouse-insurer-address %>
			</p>
		</div>
		<div class="line-fourteen spouse-insurer-policy-holder">
			<p>
				<%#= user.form.spouse-insurer-policy-holder %>
			</p>
		</div>
		<div class="line-fourteen spouse-insurer-coverage">
			<p>
				<%#= user.form.spouse-insurer-policy-holder %>
			</p>
		</div>
		<div class="line-fifteen spouse-employer-name">
			<p>
				<%#= user.form.spouse-employer-name %>
			</p>
		</div>
		<div class="line-fifteen spouse-employer-address">
			<p>
				<%#= user.form.spouse-employer-address %>
			</p>
		</div>
		<div class="line-fifteen spouse-employer-phone">
			<p>
				<%#= user.form.spouse-employer-phone %>
			</p>
		</div>
		<div class="line-sixteen spouse-employer-city">
			<p>
				<%#= user.form.spouse-employer-city %>
			</p>
		</div>
		<div class="line-sixteen spouse-employer-zip">
			<p>
				<%#= user.form.spouse-employer-zip %>
			</p>
		</div>
		<div class="line-eighteen emergency-name">
			<p>
				<%= user.form.emergencies[0].name %>
			</p>
		</div>
		<div class="line-eighteen emergency-address">
			<p>
				<%= user.form.emergencies[0].address %>
			</p>
		</div>
		<div class="line-eighteen emergency-relationship">
			<p>
				<%= user.form.emergencies[0].relationship_to_patient %>
			</p>
		</div>
		<div class="line-eighteen emergency-phone">
			<p>
				<%= user.form.emergencies[0].phone_number %>
			</p>
		</div>
		<div class="line-nineteen emergency-name-2">
			<p>
				<%= user.form.emergencies[1].name %>
			</p>
		</div>
		<div class="line-nineteen emergency-address-2">
			<p>
				<%= user.form.emergencies[1].address %>
			</p>
		</div>
		<div class="line-nineteen emergency-relationship-2">
			<p>
				<%= user.form.emergencies[1].relationship_to_patient %>
			</p>
		</div>
		<div class="line-nineteen emergency-phone-2">
			<p>
				<%= user.form.emergencies[1].phone_number %>
			</p>
		</div>
	</div>
</div>

app/views/offices/_form.html.erb
<%= nested_form_for @office do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="demoBackground">
    <table>
      <tr>
        <td class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </td>
        <td class="field">
          <%= f.label :address %>
          <%= f.text_field :address %>
        </td>
      </tr>
      <tr>
        <td class="field">
          <%= f.label :city %>
          <%= f.text_field :city %>
        </td>
        <td class="field">
          <%= f.label :state %>
          <%= f.text_field :state %>
        </td>
      </tr>
      <tr>
        <td class="field">
          <%= f.label :zipcode %>
          <%= f.text_field :zipcode %>
        </td>
        <td class="field">
          <%= f.label :phone %>
          <%= f.text_field :phone %>
        </td>
      </tr>
      <tr>
        <td class="field">
          <%= f.label :fax %>
          <%= f.text_field :fax %>
        </td>
        <td class="field">
          <%= f.label :email %>
          <%= f.text_field :email %>
        </td>
      </tr>
      <tr>
        <td class="field">
          <%= f.label :abbreviation %>
          <%= f.text_field :abrv %>
        </td>
      </tr>
      <tr>
          <!-- <%#= f.fields_for :pdf do |pdf| %>
            <td><%#= pdf.label :form_name, class: "sign" %>
            <%#= pdf.text_field :form_name %></td>
              <br /><br />
            <td><%#= pdf.file_field :pdf_form %></td>
        <%# end %>
      </tr> -->
      <tr>
        <td class="actions">
          <%= f.submit "Submit Office!", class: "submit-button eligibility margin-top" %>
          <%= link_to "Cancel", offices_path, class: "removeButton signin-button margin-top" %>
        </td>
      </tr>
    </table>
  </fieldset>
<% end %>

app/views/offices/_new_appointment.html.erb
<%= form_for :appointment do |f| %>
	<%= f.check_box :tos_priv %> By checking the box and clicking "OK", you agree to abide by our Terms of Service and Privacy Policy.<br />
	<%= f.submit "I Agree!", class: "submit-button" %>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Doctor's Office Registry</h1>
 
  
 <div id="accordion">
      <% @offices.each_with_index do |office, index| %>
        <h3>
            <a href="#" data-abrv="<%=office.abrv%>"><%= office.name %></a>
        </h3>
        <div class="accordion_<%=office.id%>">
          <p>
            <b>Address:</b>
            <%= office.address %>
          </p>
          <p>
            <b>City:</b>
            <%= office.city %>
          </p>
          <p>
            <b>State:</b>
            <%= office.state %>
          </p>
          <p>
            <b>Zipcode:</b>
            <%= office.zipcode %>
          </p>
          <p>
            <b>Phone Number:</b>
            <%= office.phone %>
          </p>
          <p>
            <b>Fax Number:</b>
            <%= office.fax %>
          </p>
          <!-- <p>
             <i><%#= link_to 'Go to Office Details >>', office %></i>
          </p> -->
          <ul class="inline-block" id="office_<%=office.id%>">
            <li>
              <button value=<%= office.id %> id="appt" class="createButton inline">View Office Form</button>
            </li>
            <li>
                 <button id="office_<%=office.id%>" class="pdfButton office-form-download">Download PDF</button> 
            </li>
          </ul>
          <br /><br /><br />
           <div class="tos_agreement" id="office_<%=office.id%>">

                <%= form_for(@receipt, :url => :receipt) do |f| %>
                  <!-- <p id="TOS" title"Terms of Service and Privacy Policy Agreement" class="legal">By checking the button below, you agree to abide by our Terms of Service and Privacy Policy.</p> -->
                  <%= f.check_box :tos_priv, :id => "tos_#{office.id}" %>

                  <p>
                    By checking the box and clicking "I Agree", you agree to abide by our <a href="http://www.happyhealth.me/terms.html" title="Go to Terms of Service Agreement" target="_blank" class="agreement_links">Terms of Service</a> and you consent to our <a href="http://www.happyhealth.me/privacy.html" title="Go to Privacy Policy" target="_blank" class="agreement_links">Privacy Policy</a>.
                  </p>

                  <%= f.hidden_field :office_id, :value => office.id %>

                  <%= f.hidden_field :user_id, :value => current_user.id %>

                  <%= f.submit 'I Agree', :class => "submit_tos submit-button", :id => office.id %>
                <% end %>
           </div>
        </div>
      <% end %>
  </div>
<br />

<% if current_user.is_admin != true %>
  
<% else %>
  <%= link_to 'Add a New Office', new_office_path %>
<% end %>

<!-- <div class="hidden">
  <%#= @office_form_partials.each do |partial| %>
    <%#= render partial %>
  <%# end %>
</div> -->

<%= render '/appointments/forms/mada.pdf.html.erb' %>

<%= render '/appointments/forms/clsma.pdf.html.erb' %>

<%= render '/appointments/forms/mhc.pdf.html.erb' %>

<%= render '/appointments/forms/sawlani_demographics.pdf.html.erb' %>

<%#= render '/appointments/forms/wpd.pdf.html.erb' %>

app/views/offices/new.html.erb
<h1>Add a New Office to the Database</h1>

<%= render 'form' %>

<%= link_to 'Back to Office List', offices_path %>

app/views/offices/show.html.erb
<%= link_to "Download PDF", office_path(@office, :format => 'pdf'), id: "pdf_link" %>

<%= render @partial_abrv %>

app/views/offices/show_old.html.erb
<p id="notice"><%= notice %></p>

<div class="dashAppointments margin-top">
  <section class="right">
    <p>
      <%= link_to "Add a new form", new_office_pdf_path(@office) %>
    </p>
    <p>
      <% @pdfs.each do |pdf| %>
        <%= image_tag pdf.pdf_form.url(:small) %><br />
        <%= link_to pdf.form_name, office_pdf_path(@office, pdf) %><br />
      <% end %>
    </p>
  </section>
  <section>
    <h2>
      <%= link_to "Download PDF", office_path(@office, :format => 'pdf') %>
    </h2>
    <p>
      <b>Office Name:</b>
      <%= @office.name %>
    </p>

    <p>
      <b>Address:</b>
      <%= @office.address %>
    </p>

    <p>
      <b>City:</b>
      <%= @office.city %>
    </p>

    <p>
      <b>State:</b>
      <%= @office.state %>
    </p>

    <p>
      <b>Zipcode:</b>
      <%= @office.zipcode %>
    </p>

    <p>
      <b>Phone Number:</b>
      <%= @office.phone %>
    </p>

    <p>
      <b>Fax Number:</b>
      <%= @office.fax %>
    </p>
    <dl>
      <dt>Physicians:</dt>
        <% @office.sorted_doctors.each do |doctor| %>
          <dd><%= doctor.title %></dd>
        <% end %>
    </dl>
    <!-- <ul class="inline-block">
      <li>
        <button value=<%= @office.id %> id="appt" class="createButton inline">View Office Form</button>
      </li>
        <div id="edit-form" class="office-form-download"> <!-- Test Button
          <button class="pdfButton office-form-download">
            Download PDF
          </button>
          <p id="TOS" title"Terms of Service and Privacy Policy Agreement" class="legal">
            <%#= form_for @appointment do |f| %>
              <%#= f.check_box_tag :tos_priv %> By checking the box and clicking "OK", you agree to abide by our Terms of Service and Privacy Policy.
            <%# end %>
          </p>
        </div>
      </li>
    </ul> -->

    <% if current_user.is_admin != true %>
      <%= link_to 'Back to Office List', offices_path %>
    <% else %>
      <%= link_to 'Edit Details', edit_office_path(@office) %> |
      <%= link_to 'Delete Office', @office, method: :delete, data: { confirm: 'Are you sure?' } %> |
      <%= link_to 'Back to Office List', offices_path %>
    <% end %>    

  </section>
</div>

app/views/offices/yelp_search.html.erb
<h1>Yelp Responses</h1>

<h2>Yelp Stats</h2>
<p>
	<strong>Average Rating: </strong><img src="<%=@response['businesses'][1]['rating_img_url']%>" />
</p>
<p>
	<strong>Total Reviews: </strong><%= @response["businesses"][1]["review_count"] %> 
</p>
<p>
	<%= @response["businesses"][1]["reviews"][0]["text_excerpt"] %> <%= link_to "Read more", @response["businesses"][1]["reviews"][0]["url"], target: "_blank" %>
</p>
<p>
	<%= @response["businesses"][1]["reviews"][1]["text_excerpt"] %> <%= link_to "Read more", @response["businesses"][1]["reviews"][1]["url"], target: "_blank" %>
</p>
<p>
	<%= @response["businesses"][1]["reviews"][2]["text_excerpt"] %> <%= link_to "Read more", @response["businesses"][1]["reviews"][2]["url"], target: "_blank" %>
</p>
<p>
	<%= link_to "See all reviews", @response["businesses"][1]["url"], target: "_blank" %>
</p>
	