config/routes.rb
HappyHealth::Application.routes.draw do

  

  get "blue_button/receive_attachment"

  captcha_route

  # get "users/show" => 'users#show'

  resources :notes

  #get '/users/sign_up' => 'static_pages#home'

  root to: "static_pages#home"

  get "/help" => 'static_pages#help'
  get "/about" => 'static_pages#about'

  post "/agree" => "offices#save_receipt", as: :receipt

  get "/add_medication" => 'forms#add_medication', as: :add_medication
  get "/remove_medication" => 'forms#remove_medication', as: :remove_medication
  get "/add_allergy" => 'forms#add_allergy', as: :add_allergy
  get "/remove_allergy" => 'forms#remove_allergy', as: :remove_allergy
  get "/add_problem" => 'forms#add_problem', as: :add_problem
  get "/remove_problem" => 'forms#remove_problem', as: :remove_problem

# Override Devise login
#  devise_for :users

  resources :users do
    resources :notes
    resources :forms do
      member do
        get 'printout'          
      end
      get 'print', on: :member
    end
    resources :appointments
  end

  #Session Routes
  get "enter" => 'sessions#new', as: 'enter'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match "/users/:id/sign_in" => "users#sign_in"

  resources :offices do
    resources :pdfs
  end

  #Yelp Office Search
  match "/yelp" => "offices#yelp_search"


  # InsuranceQuery GET resources & requests
  resources :insurance_queries do
    #get 'eligibility', on: :collection
    get 'eligibility', on: :member
    put 'service', on: :member
  end

  #********************** DOWNLOAD PDF BUTTON ****************************

  get "/appointment/download/:appointment_id" => 'offices#show', :as => :pdf
  get "/office/download/:office_id" => 'offices#show_pdf', :as => :office_pdf

  #########################################################################
  # AJAX get requests
  get "/appointment/doctors" => 'appointments#get_doctors'
  get "/appointment/pdf" => 'appointments#get_pdf'
  #########################################################################

  get "/doctors" => 'appointments#doctors', :as => :doctors

  match "/officeforms/new" =>'pdfs#new'

  # BlueButton Direct CCDA Attachment Routing
  post "/incoming/ccda/for/:to" => 'bluebutton#attachment'

end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  attr_accessible :form_name,
                  :office_id,
                  :pdf_form

  has_attached_file :pdf_form, styles: {
                                          small: "150x150>",
                                          large: "800X1200>"
                                      },
  					# :default_url => lambda { |a| "#{a.instance.create_default_url}" }
  					# default_url: ActionController::Base.helpers.asset_path("/missing/:style.png"
  					url: "/app/assets/images/:attachment/:id/:style/:basename.:extension",
            path: ":rails_root:url"


  # belongs_to :office, dependent: :destroy

  # def create_default_ul
  # 	   ActionController::Base.helpers.asset_path("/missing/:style.png", :digest => false)
  # end

end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController

  before_filter :get_office
  before_filter :logged_in
  before_filter :get_user
  before_filter :admin_user_access, except: [:index, :show]

  def get_office
  	@office = Office.find params[:office_id]
  end

  def index
  	@pdfs = Pdf.find_all_by_office_id params[:office_id]
  end

  def new
   @pdf = Pdf.new
  end

  def edit
  	@pdf = Pdf.find_by_id params[:id]
  end

  def create
  	@pdf = Pdf.new(params[:pdf])

  	if @pdf.save
  		redirect_to office_path(@office), notice: 'New office form added!'
  	else
  		render action: 'new', notice: 'Sorry, an error occurred. Please try again.'
  	end
  end

  def update
  	@pdf = Pdf.find_by_id params[:id]

  	if @pdf.update_attributes params[:pdf]
  		redirect_to office_path(@office), notice: 'Office form edited!'
  	else
  		render action: 'new', notice: 'Sorry, an error occurred. Please try again.'
  	end
  end

  def show
  	@pdf = Pdf.find params[:id]
  end

  def destroy
  	@pdf = Pdf.find_by_id params[:id]
  	@pdf.destroy
  	redirect_to office_path@office, notice: "Office form deleted"
  end

end

app/views/pdfs/_pdf_form.html.erb
<%= form_for [@office, @pdf], html: { multipart: true } do |f| %>
	<div class="signup pdf-upload">
		<%= f.hidden_field :office_id, value: params[:office_id] %>
		<%= f.label :form_name, class: "sign" %>
	    <%= f.text_field :form_name %>
	    <br /><br />
	    <%= f.file_field :pdf_form %>  
	    <br /><br />
	    <%= f.submit "Submit Office Form!", class: "submit-button eligibility" %><br />
	    <%= link_to "Cancel", offices_path, class: "removeButton signin-button" %>
	</div>
<% end %>

app/views/pdfs/edit.html.erb
<h1>
	<%= "Edit #{@office.name}\'s Office Form" %>
</h1>

<%= render "pdf_form" %>

app/views/pdfs/index.html.erb
<h1><%= "#{@office.name}\'s Forms Page" %></h1>

<div class="dashAppointments margin-top">

	<p>
		<%= link_to "<< Back to #{@office.name} Office Page", office_path(@office) %> |
		<%= link_to "All Offices", offices_path %>
	</p>
	<br />
	<% @pdfs.each do |pdf| %>
		<p class="left margin-right">
			<%= image_tag pdf.pdf_form.url(:medium) %> <br /><br />
			<%= link_to "View Form", office_pdf_path(@office, pdf) %> |
			<%= link_to "Edit", edit_office_pdf_path(@office, pdf) %> |
			<%= link_to "Delete", [@office, pdf], method: :delete, confirm: "Are you sure you want to delete the #{pdf.form_name.titleize} Form?" %><br /><br />
		<p>
	<% end %>
</div>

app/views/pdfs/new.html.erb
<h1>Office PDF Form</h1>

<%= render 'pdf_form' %>

app/views/pdfs/show.html.erb
<h1><%= "#{@office.name}\'s #{@pdf.form_name.titleize} Form" %></h1>

<div class="dashAppointments margin-top">

	<p>
		<%= link_to 'Edit', edit_office_pdf_path(@office, @pdf) %> |
		<%= link_to "Delete", [@office, @pdf], method: :delete, confirm: "Are you sure you want to delete the #{@pdf.form_name.titleize} Form?" %> |
		<%= link_to "All Office Forms", office_pdfs_path(@office) %> |
		<%= link_to "#{@office.name} Main Page", office_path(@office) %>
	</p>
	<br />
	<p>
		<%= image_tag @pdf.pdf_form.url(:medium) %>
	</p>	

</div>