config/routes.rb
HappyHealth::Application.routes.draw do

  

  get "blue_button/receive_attachment"

  captcha_route

  # get "users/show" => 'users#show'

  resources :notes

  #get '/users/sign_up' => 'static_pages#home'

  root to: "static_pages#home"

  get "/help" => 'static_pages#help'
  get "/about" => 'static_pages#about'

  post "/agree" => "offices#save_receipt", as: :receipt

  get "/add_medication" => 'forms#add_medication', as: :add_medication
  get "/remove_medication" => 'forms#remove_medication', as: :remove_medication
  get "/add_allergy" => 'forms#add_allergy', as: :add_allergy
  get "/remove_allergy" => 'forms#remove_allergy', as: :remove_allergy
  get "/add_problem" => 'forms#add_problem', as: :add_problem
  get "/remove_problem" => 'forms#remove_problem', as: :remove_problem

# Override Devise login
#  devise_for :users

  resources :users do
    resources :notes
    resources :forms do
      member do
        get 'printout'          
      end
      get 'print', on: :member
    end
    resources :appointments
  end

  #Session Routes
  get "enter" => 'sessions#new', as: 'enter'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  match "/users/:id/sign_in" => "users#sign_in"

  resources :offices do
    resources :pdfs
  end

  #Yelp Office Search
  match "/yelp" => "offices#yelp_search"


  # InsuranceQuery GET resources & requests
  resources :insurance_queries do
    #get 'eligibility', on: :collection
    get 'eligibility', on: :member
    put 'service', on: :member
  end

  #********************** DOWNLOAD PDF BUTTON ****************************

  get "/appointment/download/:appointment_id" => 'offices#show', :as => :pdf
  get "/office/download/:office_id" => 'offices#show_pdf', :as => :office_pdf

  #########################################################################
  # AJAX get requests
  get "/appointment/doctors" => 'appointments#get_doctors'
  get "/appointment/pdf" => 'appointments#get_pdf'
  #########################################################################

  get "/doctors" => 'appointments#doctors', :as => :doctors

  match "/officeforms/new" =>'pdfs#new'

  # BlueButton Direct CCDA Attachment Routing
  post "/incoming/ccda/for/:to" => 'bluebutton#attachment'

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController

  before_filter :current_user
  before_filter :printout, only: :print

  def show
    @form = Form.find_by_user_id(params[:user_id])
    @user = User.find_by_id params[:user_id]
    @current_page = "profile_show"
    @total_allergies = @user.form.medical.allergies.count

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @form }
    end
  end

  def new
    @user = User.find_by_id(params[:user_id])

    if @user.form
      @form = @user.form
    else
      @form = Form.new

      @form.user_id = params[:user_id]
      @form.personal = Personal.new
      2.times { @form.emergencies << Emergency.new }
      @form.insurances <<  Insurance.create(:title => "Primary")
      @form.insurances << Insurance.create(:title => "Secondary")
      @form.dental << Dental.new
      @form.vision << Vision.new
      @form.responsible = Responsible.new
      @form.medical = Medical.new
      3.times { @form.medical.allergies << Allergy.new }
      3.times { @form.medical.medications << Medication.new }
      3.times { @form.medical.problems << Problem.new }
      @form.save
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @form }
    end
  end

  def edit
    @form = Form.find(params[:id])
    @user = User.find_by_id(@form.user_id)
    @current_page = "profile_show"
  end

  def create
    @form = Form.new(params[:form])

    respond_to do |format|
      if @form.save
        format.html { redirect_to user_form_path(current_user.id, @form.id), notice: 'Your HappyHealth Form was successfully created.' }
        format.json { render json: @form, status: :created, location: @form }
      else
        format.html { render action: "new" }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @form = Form.find(params[:id])
    @user = User.find_by_id(@form.user_id)
    respond_to do |format|

      @form.update_activity params

      # Auto-update Insurance "Self" Policy Holder with Personal Info
      if (@form.insurances[0].relationship_to_patient).downcase == "self"

        pers = @user.form.personal

        @form.insurances[0].update_attributes(
          subscribers_last_name: pers.last_name,
          subscribers_first_name: pers.first_name,
          middle_initial: nil,
          subscribers_address: pers.address,
          subscribers_city: pers.city,
          subscribers_state: pers.state,
          subscribers_zipcode: pers.zip_code,
          social_security: "",
          birthdate: pers.date_of_birth,
          sex: pers.gender,
          subscribers_phone: pers.home_phone,
          subscribers_employer: pers.employer
        )

      end

      format.html { redirect_to user_form_path(current_user.id), notice: 'Your HappyHealth Form was successfully updated.' }
      format.json { head :no_content }
    end
  end

  def destroy
    @form = Form.find_by_id(params[:id])
    @user = User.find_by_id(@form.user_id)
    @form.destroy

    respond_to do |format|
      format.html { redirect_to @user }
      format.json { head :no_content }
    end
  end

  def add_medication
    @form = Form.find(params[:form_id])
    @medication = Medication.new
    @form.medical.medications << @medication

    respond_to do |format|
      format.js { render "forms/Medical/Medication/add_medication" }
    end
  end

  def remove_medication
    @medication = Medication.find(params[:medication_id])
    @medication.medical.form.create_activity :remove_medical, parameters: {:info => @medication.info, :reason => @medication.reason}, owner: @medication.medical.form.user, recipient: @medication
    @medication.destroy

    respond_to do |format|
      format.js { render "forms/Medical/Medication/remove_medication" }
    end
  end

  def add_allergy
    @form = Form.find(params[:form_id])
    @allergy = Allergy.new
    @form.medical.allergies << @allergy
    respond_to do |format|
      format.js { render "forms/Medical/Allergy/add_allergy" }
    end
  end

  def remove_allergy
    @allergy = Allergy.find(params[:allergy_id])
    @allergy.medical.form.create_activity :remove_medical, parameters: {:info => @allergy.info, :reason => @allergy.reaction, :severity => @allergy.severity}, owner: @allergy.medical.form.user, recipient: @allergy
    @allergy.destroy

    respond_to do |format|
      format.js { render "forms/Medical/Allergy/remove_allergy" }
    end
  end

  def add_problem
    @form = Form.find(params[:form_id])
    @problem = Problem.new
    @form.medical.problems << @problem
    respond_to do |format|
      format.js { render "forms/Medical/Problem/add_problem" }
    end
  end

  def remove_problem
    @problem = Problem.find(params[:problem_id])
    @problem.medical.form.create_activity :remove_medical, parameters: {:condition => @problem.condition, :status => @problem.status, :age_onset => @problem.age_onset}, owner: @problem.medical.form.user, recipient: @problem
    @problem.destroy

    respond_to do |format|
      format.js { render "forms/Medical/Problem/remove_problem" }
    end
  end

  # **************** FORM PRINTOUTS ******************

  def printout
    @user = User.find_by_id params[:user_id]
    @form = Form.find_by_id params[:id]
    @current_page = "printout"

    @personal = @user.form.personal
    @med_1 = @user.form.medical.medications[0]
    @med_2 = @user.form.medical.medications[1]
    @allergies = @user.form.medical.allergies
    @contact_1 = @user.form.emergencies[0]
    @contact_2 = @user.form.emergencies[1]
    @appt = @user.appointments
  end

  def print
    @long_height = "long-height"
    get_stylesheet = "#{Rails.root}/app/assets/stylesheets/happy_health.css.scss.erb"
    # if Rails.env.production?
    #   get_stylesheet = "#{Rails.root}/app/assets/stylesheets/#{abrv}.css.scss.erb"
    # else
    #   get_stylesheet = "#{Rails.root}/app/assets/stylesheets/#{abrv}.css.scss.erb"
    # end
    
    respond_to do |format|
      html = render_to_string(
        :layout => "pdf.html.erb" ,
        :action => "print.html.erb",
        :formats => [:html],
        :handler => [:erb]
      )
      kit = PDFKit.new(html)
      kit.stylesheets << get_stylesheet
      send_data(kit.to_pdf,
        :filename => "#{@user.to_s}_Health_Form.pdf",
        :type => 'application/pdf'
        )
      return # to avoid double render call
    end
  end


    #Send Fax, receive confirmation
    # @fax = Phaxio.send_fax(to: '15555555555', string_data: "hello world")
    # Phaxio.get_fax_status(id: @fax["faxId"])

    # # Get a Fax and save it as a PDF
    # @pdf = Phaxio.get_fax_file(id: @fax["faxId"], type: "p")
    # File.open("received_test.pdf", "w") do |file|
    #   file << @pdf
    # end
end

app/helpers/forms_helper.rb
module FormsHelper

	def values_of_activity_hash hash
		values = []
		hash.values.each do |val|
			if val.class.to_s == "Hash"
				puts val
				values << values_of_activity_hash(val)
			else
				values << val
			end
		end
		values.flatten.map {|o| o.to_s}.reject { |c| c.empty? }
	end
end

app/views/forms/_form.html.erb
<%= form_for [@user, @form] do |f| %>
	<% if @form.errors.any? %>
    	<div id="error_explanation">
      		<h2><%= pluralize(@form.errors.count, 			
			"error") %> prohibited this form from being saved:</h2>

      		  <ul>
		      	<% @form.errors.full_messages.each do |msg| %>
		        	<li><%= msg %></li>
		      	<% end %>
		      </ul>
	    </div>
  <% end %>

	<%# sections = ["Personal", "Responsible Party", "Emergency", "Insurance", "Medical"] %>

	<% sections = ["Personal", "Emergency", "Insurance", "Medical"] %>
	
	<div id="tabs">
		<ul class="form-tabs">
			<% sections.each_with_index do |section, index| %>
				<li><a href=<%="#tabs-#{index+1}"%>><%="#{section}"%></a></li>
			<% end %>
		</ul>
		
		<% sections.each_with_index do |section, index| %>
			<div class="form-tabs" id=<%="tabs-#{index+1}"%>>
				<% string = "/forms"+"/#{section.split(" ")[0]}" + "/#{section.split(" ")[0].downcase}" %>
				<%= render string, :f => f, :form => @form%>
			</div>
		<% end %>

	</div>
 
  	<%= f.hidden_field :user_id %>


	
			<%= f.submit "Save Progress", :class => "createButton right" %>
			 		
			<!--<%# if current_user.form %>
				<li>
					<%#= link_to 'Back', user_form_path(@form.user_id, @form), :class => 'backButton' %>
				</li>-->
			<%# else %>

			<%# end %>
<% end %>

app/views/forms/_form_printout.html.erb
<div id="form_printout" class="printout_container">
	
	<div>
		<table>
			<thead>
				<th>Demographics</th>
				<th>Medications</th>
				<th>Emergency Contacts</th>
				<th>Care Plan</th>
			</thead>
			<tbody>
				<tr>
					<td class="user-panel-image" rowspan="2">		
						
						<ul class="inline-block margin-top">
							<li class="left"><%= image_tag "patient_photo.jpg" %></li>
							<li>
								<h2 class="printout-name"><%= @user.to_s %> <%= @personal.last_name %></h2>			
								<p><%= @personal.gender %></p>
								<p><%= @user.age %></p>
								<p>Hypertension</p>								
							</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @med_1.info %></h2>
							</li> 
							<li>Administration:</li>
							<li>Start date:</li>
							<li>Type (tablet, liquid, etc.)</li>
						</ul>

					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @contact_1.name %></h2>
							</li>
							<li>
								<%= @contact_1.relationship_to_patient %>
							</li>
							<li>
								<%= "#{@contact_1.city}" + " " + "#{@contact_1.state}" + ", " + "#{@contact_1.zipcode}" %>
							</li>
							<li>
								<%= @contact_1.phone_number %>
							</li>								
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Office Consult</h2>
							<li>Instructions: Diabetes management consultation</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. George Katsoyannis</li>
						</ul>
					</td>

				</tr>
				<tr>
					
					
					
				</tr>
				<tr>
					<td>
						<h2>Conditions: </h2>
							<ul>
								<li>Diabetes</li>
								<li>Hyperlipidemia</li>
								<li>Hypertension</li>
							</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @med_2.info %></h2>
							</li> 
							<li>Administration:</li>
							<li>Start date:</li>
							<li>Type (tablet, liquid, etc.)</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @contact_2.name %></h2>
							</li>
							<li><%= @contact_2.relationship_to_patient %></li>
							<li><%= @contact_2.address %></li>
							<li>
								<%= "#{@contact_2.city}" + " " + "#{@contact_2.state}" + ", " + "#{@contact_2.zipcode}" %>
							</li>
							<li><%= @contact_2.phone_number %></li>					
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Sputuum Culture</h2>
							<li>Date: 6/16/2012</li>
							<li>Facility: Lutheran General</li>						
						</ul>
					</td>
				</tr>
				
			</tbody>
			
		</table>

		<table>
			<thead>
				<th>Allergies</th>
				<th>Procedures</th>
				<th>Immunizations</th>
				<th>Encounters</th>
			</thead>
			<tbody>
				<tr>
					<td><h2><%= @allergies[0].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>	
					<td rowspan="2">
						<ul>
							<h2>Lumbar Spine Surgery</h2>
							<li>Date: 1/1/2013</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. Christopher Dewald</li>
						</ul>

					</td>
					<td rowspan="2">						
						<ul>
							<h2>Influenza virus vaccine</h2>
							<li>Sept 15, 2012 </li>
							<li>Condition</li>
							<li>Note:</li>
						</ul>
					</td>
					<td rowspan="2">						
						<ul>
							<h2>Encounter type:</h2>
							<li><%= @appt.last.appt_date.strftime("%b %d, %Y") %>
							</li>
							<li></li>
							<li><strong>Provider:</strong> <%= @appt.last.doctor.title %></li>
						</ul>
					</td>
				</tr>
				<tr>
					<td><h2><%= @allergies[1].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>
					
					
				</tr>
				<tr>
					<td><h2><%= @allergies[2].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Cesarian Section</h2>
							<li>Date: 1/1/2013</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. Elena Koogan</li>
						 </ul>

					</td>
					<td rowspan="2">
						<h2>Tetnus</h2>
							<ul>
								<li>June 9, 2012 </li>
								<li>Condition</li>
								<li>Note:</li>
							</ul>
					</td>
					<td rowspan="2"> 
						<ul>
							<h2>Encounter type</h2>
							<li></li>
							<li></li>
						</ul>
					</td>
				</tr>
							
			</tbody>
		</table>
	</div>
</div>

app/views/forms/edit.html.erb
<!--<ul class="alert inline-block">
	<li>
		<strong>
			NOTICE: This is a PUBLIC, TEST environment. Information could potentially be seen by others when you leave. Don't use authentic information. 
		</strong>
	</li>
	<li class="alert-close">X</li>
</ul>-->

<h1>Edit your Form</h1>

<%= render 'form'%>

app/views/forms/new.html.erb
<h1>Your Form</h1>

  <%= render 'form' %>


<%#= link_to 'Back', current_user, :class => "button form-back" %>

app/views/forms/print.html.erb
<%= render 'form_printout' %>

app/views/forms/printout.html.erb
<%#= wicked_pdf_stylesheet_link_tag 'mpd' %>

<ul class="left margin-top margin-bottom inline">
	<li>
		<%= link_to '<< Back to Health Profile', user_form_path(current_user.id, current_user.form.id), class: "submit-button" %>
	</li>
	<li>
		<%= link_to image_tag("BlueButton_Icon.gif", class: "icon") + "Download",  print_user_form_path(current_user.id, current_user.form.id), class: "submit-button" %>
	</li>

</ul>

<div id="form_printout" class="margin-top clear">
	
	<div>
		<table>
			<thead>
				<th>Demographics</th>
				<th>Medications</th>
				<th>Emergency Contacts</th>
				<th>Care Plan</th>
			</thead>
			<tbody>
				<tr>
					<td class="user-panel-image" rowspan="2">		
						
						<ul class="inline-block margin-top">
							<li class="left"><%= image_tag "patient_photo.jpg" %></li>
							<li>
								<h2 class="printout-name"><%= @user.to_s %> <%= @personal.last_name %></h2>			
								<p><%= @personal.gender %></p>
								<p><%= @user.age %></p>
																
							</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @med_1.info %></h2>
							</li> 
							<li>Administration:</li>
							<li>Start date:</li>
							<li>Type (tablet, liquid, etc.)</li>
						</ul>

					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @contact_1.name %></h2>
							</li>
							<li>
								<%= @contact_1.relationship_to_patient %>
							</li>
							<li>
								<%= "#{@contact_1.city}" + " " + "#{@contact_1.state}" + ", " + "#{@contact_1.zipcode}" %>
							</li>
							<li>
								<%= @contact_1.phone_number %>
							</li>								
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Office Consult</h2>
							<li>Instructions: Diabetes management consultation</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. George Katsoyannis</li>
						</ul>
					</td>

				</tr>
				<tr>
					
					
					
				</tr>
				<tr>
					<td>
						<h2>Conditions: </h2>
							<ul>
								<li>Diabetes</li>
								<li>Hyperlipidemia</li>
								<li>Hypertension</li>
							</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @med_2.info %></h2>
							</li> 
							<li>Administration:</li>
							<li>Start date:</li>
							<li>Type (tablet, liquid, etc.)</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>							
							<li>
								<h2><%= @contact_2.name %></h2>
							</li>
							<li><%= @contact_2.relationship_to_patient %></li>
							<li><%= @contact_2.address %></li>
							<li>
								<%= "#{@contact_2.city}" + " " + "#{@contact_2.state}" + ", " + "#{@contact_2.zipcode}" %>
							</li>
							<li><%= @contact_2.phone_number %></li>					
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Sputuum Culture</h2>
							<li>Date: 6/16/2012</li>
							<li>Facility: Lutheran General</li>						
						</ul>
					</td>
				</tr>
				
			</tbody>
			
		</table>

		<table>
			<thead>
				<th>Allergies</th>
				<th>Procedures</th>
				<th>Immunizations</th>
				<th>Encounters</th>
			</thead>
			<tbody>
				<tr>
					<td><h2><%= @allergies[0].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>	
					<td rowspan="2">
						<ul>
							<h2>Lumbar Spine Surgery</h2>
							<li>Date: 1/1/2013</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. Christopher Dewald</li>
						</ul>

					</td>
					<td rowspan="2">						
						<ul>
							<h2>Influenza virus vaccine</h2>
							<li>Sept 15, 2012 </li>
							<li>Condition</li>
							<li>Note:</li>
						</ul>
					</td>
					<td rowspan="2">						
						<ul>
							<h2>Encounter type:</h2>
							<li><%= @appt.last.appt_date.strftime("%b %d, %Y") %>
							</li>
							<li></li>
							<li><strong>Provider:</strong> <%= @appt.last.doctor.title %></li>
						</ul>
					</td>
				</tr>
				<tr>
					<td><h2><%= @allergies[1].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>
					
					
				</tr>
				<tr>
					<td><h2><%= @allergies[2].info %></h2>
						<ul>
							<li>Severity</li>
							<li>Reaction</li>
						</ul>
					</td>
					<td rowspan="2">
						<ul>
							<h2>Cesarian Section</h2>
							<li>Date: 1/1/2013</li>
							<li>Facility: Rush University Medical Center</li>
							<li>Provider: Dr. Elena Koogan</li>
						 </ul>

					</td>
					<td rowspan="2">
						<h2>Tetnus</h2>
							<ul>
								<li>June 9, 2012 </li>
								<li>Condition</li>
								<li>Note:</li>
							</ul>
					</td>
					<td rowspan="2"> 
						<ul>
							<h2>Encounter type</h2>
							<li></li>
							<li></li>
						</ul>
					</td>
				</tr>
							
			</tbody>
		</table>
	</div>
</div>

app/views/forms/show.html.erb
<!-- <p id="notice" class="success"><%= notice %><span class="close">X</span></p> -->

<h1>Your HappyHealth Form</h1>

<div class="margin-bottom">
	<ul class="inline padding-top right">
		<li>
			<%= link_to 'Edit Profile', edit_user_form_path(current_user.id, current_user.form.id), class: 'submit-button', id: "edit-form" %>
		</li>
		<!-- <li>
			<%#= link_to "Delete Profile", user_form_path(current_user.id, current_user.form.id), :method => 'delete',  data: { confirm: 'Are you sure you want to delete your profile #{user.form.personal.first_name}? You will lose all your saved data.' }, :class => 'removeButton block' %>
		</li> -->
		<!--<li>
			<%#= link_to "View Printout",  printout_user_form_path(current_user.id, current_user.form.id), class: "submit-button" %>
		</li>-->
	</ul>
</div>

<div id="tabs" class="margin-top clear">
	<ul class="form-tabs">
		<li><a href="#tabs-1"><span class="icon"><%= image_tag "health_prof_small.gif" %></span>Personal</a></li>
		<!--<li><a href="#tabs-2">Responsible Party</a></li>-->
		<li><a href="#tabs-2"><span class="icon"><%= image_tag "emergency.gif" %></span>Emergency</a></li>
		<li><a href="#tabs-3"><span class="icon"><%= image_tag "ins_card_small.gif" %></span>Insurance</a></li>
		<li><a href="#tabs-4"><span class="icon"><%= image_tag "vitals.gif" %></span>Medical</a></li>
	</ul>

	<div id="tabs-1">
		<%= render '/forms/Personal/personal_show', :form => @form %>
	</div>
	<!-- <div id="tabs-2">
		<%#= render '/forms/Responsible/responsible_show', :form => @form %>
	</div> -->
	<div id="tabs-2">
		<%= render '/forms/Emergency/emergency_show', :form => @form %>
	</div>
	<div id="tabs-3">
		<%= render '/forms/Insurance/insurance_show', :form => @form %>
	</div>
	<div id="tabs-4">
		<%= render '/forms/Medical/medical_show', :form => @form %>
	</div>
</div>